config/routes.rb
Rails.application.routes.draw do

resources :blogs, :path => "/images"
resources :guidelines, :path => "/guidelines", via: [:get, :post]

end

app/models/blog.rb
require 'open-uri' 
class Blog < ActiveRecord::Base
  attr_accessor :crop_x, :crop_y, :crop_w, :crop_h
  
	def self.search(search)
	  if search
		self.where("title || description like ?", "%#{search}%")
	  else
		self.all
	  end
	end
   
  def cropping?
    !crop_x.blank? && !crop_y.blank? && !crop_w.blank? && !crop_h.blank?
  end 
  def slug
    description.downcase.gsub(" ", "-")  
  end	
  def to_param
  	"#{id}-#{slug}"
  end	

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
helper_method :logged_in?

def logged_in?
  session[:login]
end

private
def authenticate
  login = authenticate_or_request_with_http_basic do |username, password|
    username == "machinas" && password == "admin"
  end
  session[:login] = login
end

def do_logout
  session[:login] = nil
end
end

app/controllers/blogs_controller.rb
require 'open-uri'
class BlogsController < ApplicationController
  before_filter :authenticate
  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  # GET /blogs
  # GET /blogs.json
  def index
  @blogs = Blog.search(params[:search])
  end
  # GET /blogs/1
  # GET /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  render "cropper"
  end

  # POST /blogs
  # POST /blogs.json
  def create
    
    @blog = Blog.new(blog_params)
      if @blog.save
        render "cropper"
      else
        render :new 
      end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Image was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Image crop was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
   def guidelines
    # put any code here that you need 
    # (although for a static view you probably won't have any)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :description, :image, :link, :crop_x, :crop_y, :crop_w, :crop_h)
    end
end

app/controllers/guidelines_controller.rb
require 'open-uri'
class GuidelinesController < ApplicationController
   def guidelines
    # put any code here that you need 
    # (although for a static view you probably won't have any)
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/cropper.html.erb
<style>

#dropzone {
			box-sizing: border-box;
			position: absolute;
			top: 0%;
			left: 0%;
			width: 100%;
			height: 100%;
			border: 2px #ababab dashed;
			text-transform: uppercase;
			font-weight: bold;
			z-index: 2;
		}
		.powered-by {
			position: absolute;
			bottom: 10px;
			left: 0;
			width: 100%;
			text-align: center;
			text-transform: none;
			font-weight: light;
			font-size: 12px;
			line-height: 1.5em;
		}
		.powered-by a {
			color: #92C7FF;
			text-decoration: none;
		}
		#image {
			text-align: center;
		}
		#view-button {
			position: fixed;
			top: 0;
			right: 0;
			padding: 10px;
			font-weight: bold;
			font-size: 10px;
			background-color: #333;
			color: #FFF;
			cursor: pointer;
			z-index: 100;
			text-transform: uppercase;
		}
		#livepreview {
			position: relative;
			top: -100px;
			width: 1200px;
			margin: 0 auto;
			z-index: 99;
		}
		.row {
			display: none;
			position: relative;
			z-index: 99;
			opacity: 0;
			padding: 50px 0;
			border-bottom: 1px dashed #333;
		}
		.row:nth-child(odd) {
			background-color: rgba(0,0,0,.05);
		}
		.preview-image {
			line-height: 0;
		}
		.preview-image {
			display: inline-block;
		}
		.preview-image, .cropped-image > div {
			position: relative;
			text-align: left;
		}
		.cropped-image {
			position: absolute;
			overflow: hidden;
		}
		.preview-image:before {
			content: " ";
			display: block;
			width: 100%;
			height: 100%;
			background-color: #000;
			position: absolute;
			opacity: .7;
		}
		.cropping-code {
			margin: 10px auto 50px;
			display: block;
			width: 100%;
			padding: 10px 0;
			text-align: center;
			border: none;
			outline: none;
			background-color: transparent;
		}
		#livepreview .cropping-code {
			box-sizing: border-box;
			position: absolute;
			bottom: 0;
			margin: 0;
			padding: 40px;
			background-color: rgba(0,0,0,0.5);
			color: #FFF;
			font-weight: bold;
		}
		.error {
			background-color: rgba(255,0,4,.2) !important;
		}
		.clear {
			width: 100%;
			clear: both;
		}
		#progress {
			position: absolute;
			top: 0;
			left: 0;
			width: 100%;
			height: 100%;
			opacity: 0;
		}
		#progress .tip {
			position: absolute;
			left: 50%;
			display: block;
			width: 80vw;
			margin-top: 2em;
			font-weight: normal;
			text-transform: none;
			
			-webkit-transform: translateX(-50%);
			-moz-transform: translateX(-50%);
			transform: translateX(-50%);
		}
		.text {
			position: absolute;
			top: 50%;
			left: 50%;
			text-align: center;
			font-size: 24px;
			font-weight: bold;
			text-transform: uppercase;
			-webkit-transform: translate(-50%,-50%);
			-moz-transform: translate(-50%,-50%);
			transform: translate(-50%,-50%);
		}
		@keyframes rotate {
			from {-webkit-transform: rotate(0deg);-moz-transform: rotate(0deg);transform: rotate(0deg);}
			to {-webkit-transform: rotate(360deg);-moz-transform: rotate(360deg);transform: rotate(360deg);}
		}
		.animation {
			position: absolute;
			top: 45%;
			left: 50%;
			-webkit-transform: translate(-50%,-50%);
			-moz-transform: translate(-50%,-50%);
			transform: translate(-50%,-50%);
			width: 35px;
			height: 35px;
			
		}
		.rotate {
			-webkit-box-sizing: border-box;
			-moz-box-sizing: border-box;
			box-sizing: border-box;
			width: 100%;
			height: 100%;
			
			-webkit-animation: rotate 3s linear infinite;
			-moz-animation: rotate 3s linear infinite;
			animation: rotate 3s linear infinite;
			
			border-radius: 50%;
			border: 3px solid #2BA800;
		}
		
		.rotate:after {
			content: " ";
			width: 12px;
			height: 12px;
			display: block;
			position: absolute;
			top: 0;
			left: 50%;
			border-radius: 50%;
			-webkit-transform: translate(-50%,-50%);
			-moz-transform: translate(-50%,-50%);
			transform: translate(-50%,-50%);
			background-color: #FFF;
		}
		img {
			-webkit-touch-callout: none;
			-webkit-user-select: none;
			-khtml-user-select: none;
			-moz-user-select: none;
			-ms-user-select: none;
			user-select: none;
			pointer-events: none;
		}
		#link{display:none;}
		#save{display:none;}
		.reupload { z-index:10; position:absolute; top:2%; left:8%; display: none;  }

		.gohome { left:2%; }
</style>	



	<div id="dropzone">
		<div class="text">
			Drop your PSD here<br />
		</div>
		<div class="powered-by">created by <a href="http://czino.de/">Eric Lehmann</a><br />powered by <a href="https://www.npmjs.com/package/psd">psd.js</a></div>
	</div>
	<div id="progress">
		<div class="text">Processing...<span class="tip"></span></div>
		<div class="animation"><div class="rotate"></div></div>
	</div>
<%= form_for @blog do |form| %>
  <% for attribute in [:link] %>
    <%= form.text_field attribute, :id => attribute %>
    <button style="z-index:10; position:absolute; top:6%; left:2%;" class="btn btn-primary" id="save">Save</button>
 <% end %>
<% end %>    
<%= link_to 'ReCrop', edit_blog_path(@blog), :class => "btn btn-warning reupload" %>
<%= link_to 'Home', blogs_path, :class => "btn btn-primary reupload gohome" %>
<script type="text/javascript">
	
	

$( document ).ready(function() {
		
		var PSD = require('psd');
		
		document.getElementById('dropzone').addEventListener('dragover', onDragOver, true);
		document.getElementById('dropzone').addEventListener('drop', onDrop, true);

		function loopThroughParents(parentGroups) {
			for (parentGroup = parentGroups.length; parentGroup >= 0; parentGroup--) {
				if (typeof parentGroups[parentGroup] != "undefined") {
					mask = parentGroups[parentGroup].get("mask");
					if (mask.left == 0 && mask.top == 0 && mask.right == 0 && mask.bottom == 0) {
						//continue
					}
					else {
						//break for loop
						console.log("layer mask found!");
						return mask;
					}
				}
			}
		}
		
		function onDragOver(e) {
		  e.stopPropagation();
		  e.preventDefault();
		  e.dataTransfer.dropEffect = 'copy';
		}
		
		function onDrop(e) {
			document.getElementById('dropzone').removeEventListener('drop', onDrop, true);
			$(".preview-image, .cropping-code").detach();
			tips = new Array(
				"Tip: you can switch between liveview and listview by pushing the button in the upper right corner",
				"Tip: you can also switch views by pressing the tab key",
				"Tip: Listview can show you hidden images (e.g. slider images)",
				"Tip: you can reverse the order within the listview by pressing the 'r'-key",
				"If croppings go wrong or something is missing ask a designer to look into this<br />Alternatively, do it yourself",

				"Xipiron is coming",
				"Take a deep breath",
				"Red links show that the cropping might be wrong"
			);
			$(".tip").html(tips[Math.floor(Math.random() * tips.length)]);
			$("#dropzone").animate({"opacity": 0}, 500, function() {
				$("#progress").animate({"opacity": 1}, 1500);
			});
			console.log("start");
			var startTime = Date.now();
	
			e.stopPropagation();
			e.preventDefault();
			
			var result = "<div id='listview'>";
			var preview = "<div id='livepreview'>";
			var seen = {};

			PSD.fromEvent(e).then(function (psd) {
			$('#save').show(10);	
			var data = psd.tree().export();
			//var data = JSON.stringify(psd.tree().export(), undefined, 2);
			nodes = psd.tree().descendants();
			for (n = 0; n < nodes.length; n++) {
				//$("#process > div").animate({"width":progress+"%"}, 100);
				progress = parseInt(n / nodes.length * 100);
				if ((nodes[n].name == "img" || nodes[n].name.toLowerCase().indexOf("image") >= 0) && typeof nodes[n].get("text") == "undefined") { 
					// group names that have img, image or slide in their names are accepted
					for (i= 0; i <= nodes[n].descendants().length; i++) {
						if (typeof nodes[n].descendants()[i] != "undefined" && typeof nodes[n].descendants()[i].get("text") == "undefined" && nodes[n].descendants()[i].get("name").toLowerCase().indexOf("rectangle") < 0 && nodes[n].descendants()[i].get("opacity") == 255) {
// loops though all children of the group until it finds a layer that is not text or rectangle // opacity must be 1!
							image = nodes[n].descendants()[i];
						}
					}
					imageName = image.get("name");
					offsetX = image.get("left");
					offsetY = image.get("top");
					width = image.get("width");
					height = image.get("height");
					if (!seen[imageName+"_"+offsetX+"_"+offsetY+"_"+width+"_"+height]) {
						// checks if the image has been handled before
						seen[imageName+"_"+offsetX+"_"+offsetY+"_"+width+"_"+height] = true;
						//console.log("Checking: "+imageName);
						imagePNG = image.toPng().outerHTML;
						
						mask = image.get("mask");
						if (mask.left == 0 && mask.top == 0 && mask.right == 0 && mask.bottom == 0) {
							parentGroups = image.ancestors();
							loopThroughParents(parentGroups);
						}
						maskX = mask.left;
						maskY = mask.top;
						maskWidth = mask.width;
						maskHeight = mask.height;
						
						croppingX = maskX - offsetX;
						croppingY = maskY - offsetY;
						croppingWidth = maskWidth;
						croppingHeight = maskHeight;
						
						croppingXRelative = croppingX / width;
						croppingYRelative = croppingY / height;
						croppingWidthRelative = croppingWidth / width;
						croppingHeightRelative = croppingHeight / height;
						if (croppingX < 0 || croppingY < 0) {
							sthIsWrong = " error";
							$('.reupload').show(10);
						}
						else {
							sthIsWrong = "";
						}
						imageName = imageName.replace(".jpg","");
						preview += "<div class='cropped-image' style='top:"+maskY+"px; left:"+maskX+"px; width:"+croppingWidth+"px; height:"+croppingHeight+"px;'>\n"+
									"<div style='top:"+(croppingY*-1)+"px; left:"+(croppingX*-1)+"px;'>"+imagePNG+"</div>\n"+
									"<input class='cropping-code"+sthIsWrong+"' value='http://images.hugoboss.com/is/image/boss/"+imageName+"?$marketing_asset$&wid="+croppingWidth+"&hei="+croppingHeight+"&cropN="+croppingXRelative+","+croppingYRelative+","+croppingWidthRelative+","+croppingHeightRelative+"' />\n"+
								"</div>\n";
						result += "<div class='row"+sthIsWrong+"'>\n"+
							"<div class='preview-image'>"+imagePNG+"\n"+
								"<div class='cropped-image' style='top:"+croppingY+"px; left:"+croppingX+"px; width:"+croppingWidth+"px; height:"+croppingHeight+"px;'>\n"+
									"<div style='top:"+(croppingY*-1)+"px; left:"+(croppingX*-1)+"px;'>"+imagePNG+"</div>\n"+
								"</div>\n"+
							"</div>";
						result += "<input class='cropping-code' value='http://images.hugoboss.com/is/image/boss/"+imageName+"?$marketing_asset$&wid="+croppingWidth+"&hei="+croppingHeight+"&cropN="+croppingXRelative+","+croppingYRelative+","+croppingWidthRelative+","+croppingHeightRelative+"' />\n"+
						"</div>";
						//console.log(progress+"%");
					}
					else {
						//console.log("Skipped '"+imageName+"' because it has been handled before");
					}
				}
				/*if (nodes[n].name == "txt") {
					console.log(nodes[n].get("left"), nodes[n].get("top"), nodes[n].get("width"), nodes[n].get("height")); // masks are also accessable for groups
				} */
			}
			preview += "</div>";
			result += "</div>";

			$("body").append(preview);
			$("body").append(result);
			$("body").append("<div id='view-button'>Liveview</div>");
			var endTime = Date.now();
			var timeDif = (endTime - startTime) / 1000;
			console.log("end: "+timeDif+"s");
			$(".row").animate({"opacity": 1}, 500);
			$("#progress").animate({"opacity": 0}, 50);
			//console.log(data);
			//document.getElementById('data').innerHTML = data;
			//document.getElementById('image').appendChild(psd.image.toPng());
			});
		}

	
	
	$(document).on('click', '.cropping-code', function() {
		$(this).select();
	});
	function changeView() {
		if ($("#view-button").text() == "Liveview") {
			$("#view-button").text("Listview");
			$(".row").show();
			$("#livepreview").hide();
		}
		else {
			$("#view-button").text("Liveview");
			$(".row").hide();
			$("#livepreview").show();
		}
	}
	function reverseOrder() {
		var list = $('#listview');
		var listItems = list.children('.row');
		list.html("");
		list.append(listItems.get().reverse());
	}
	$(document).on('click', '#view-button', function() {
		changeView();
	});






	$('#save').click(function(){


		var arr = [];
		$("#livepreview input.cropping-code").each(function(){
		    arr.push($(this).val() + '<br /><br />');
		});

		$('#link').val(arr.join(' '))

	


    ;})
	
	$('body').on('keydown', function(e) {
		if (e.which == 9) { // tab
			e.preventDefault();
			changeView();
		}
		if (e.which == 82) { // r
			e.preventDefault();
			reverseOrder();
		}
	});
});

</script>

app/views/blogs/edit.html.erb
<div class="container">
	<div class="row">
		<div class="column">
			<h1>Editing</h1>

			<%= render 'form2' %>

			<%= link_to 'Show', @blog, :class => "btn btn-info" %> |
			<%= link_to 'Back', blogs_path, :class => "btn btn-info" %>
			
	</div>
	</div>
</div>

app/views/blogs/index.html.erb
<style type="text/css">
	


div.pager {
    text-align: center;
    margin: 1em 0;
}

div.pager span {
    display: inline-block;
    width: 1.8em;
    height: 1.8em;
    line-height: 1.8;
    text-align: center;
    cursor: pointer;
    background: #000;
    color: #fff;
    margin-right: 0.5em;
}

div.pager span.active {
    background: #337ab7;
}


#loading{display: none;}

.spinner {
  width: 40px;
  height: 40px;
  margin: 100px auto;
  background-color: #333;

  border-radius: 100%;  
  -webkit-animation: sk-scaleout 1.0s infinite ease-in-out;
  animation: sk-scaleout 1.0s infinite ease-in-out;
}

@-webkit-keyframes sk-scaleout {
  0% { -webkit-transform: scale(0) }
  100% {
    -webkit-transform: scale(1.0);
    opacity: 0;
  }
}

@keyframes sk-scaleout {
  0% { 
    -webkit-transform: scale(0);
    transform: scale(0);
  } 100% {
    -webkit-transform: scale(1.0);
    transform: scale(1.0);
    opacity: 0;
  }
}
</style>


<div class="container" >
	<div class="row">
		<div class="column">
		<p id="notice"><%= notice %></p>
		<h1 class="headline">Listing Projects</h1>
		<ul class="list-inline">
        <li><%= link_to 'New Project', new_blog_path, :class => "btn btn-info" %></li>
		<li>
			<%= form_tag blogs_path, :method => 'get' do %>
			  <p style="display:inline-block"><%= submit_tag "Search", :name => nil, :class => "btn btn-primary" %> </p>

			  <p style="display:inline-block">
				<%= text_field_tag :search, params[:search] %>		
			  </p>
			<% end %>
		</li>
		<li><%= link_to 'Guidelines', guidelines_path, :class => "btn btn-info" %></li>
		</ul>
		<div class="spinner"></div>
		<table id="loading" class="table paginated" style="margin-top:30px;">
		  <thead>
			<tr>
			  <th>Brand</th>
			  <th>Project</th>
			  <th colspan="3"></th>
			</tr>
		  </thead>

		  <tbody>
			<% @blogs.reverse_each do |blog| %>
			  <tr>
				<td><%= blog.title %></td>
				<td><%= blog.description %></td>
				<td><%= link_to 'Show', blog, :class => "btn btn-primary" %></td>
				<td><%= link_to 'ReCrop', edit_blog_path(blog), :class => "btn btn-warning" %></td>
				<td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger" %></td>
			  </tr>
			<% end %>
		  </tbody>
		</table>

		<br>

		
		</div>
	</div>
</div>
<div  class="logo"><p>created by:</p><img src="<%= image_url 'logo.png' %>" alt=""></div>


<script type="text/javascript">
	

	(function() {
$('.spinner').hide(10);	
$('#loading').show(30);
$('table.paginated').each(function() {
    var currentPage = 0;
    var numPerPage = 10;
    var $table = $(this);
    $table.bind('repaginate', function() {
        $table.find('tbody tr').hide().slice(currentPage * numPerPage, (currentPage + 1) * numPerPage).show();
    });
    $table.trigger('repaginate');
    var numRows = $table.find('tbody tr').length;
    var numPages = Math.ceil(numRows / numPerPage);
    var $pager = $('<div class="pager"></div>');
    for (var page = 0; page < numPages; page++) {
        $('<span class="page-number"></span>').text(page + 1).bind('click', {
            newPage: page
        }, function(event) {
            currentPage = event.data['newPage'];
            $table.trigger('repaginate');
            $(this).addClass('active').siblings().removeClass('active');
        }).appendTo($pager).addClass('clickable');
    }
    $pager.insertAfter($table).find('span.page-number:first').addClass('active');
});

})();


</script>

app/views/blogs/new.html.erb
<div class="container">
	<div class="row">
		<div class="column">
				<h1>New image</h1>

				<%= render 'form' %>

				<%= link_to 'Back', blogs_path, :class => "btn btn-info" %>
	</div>
	</div>
</div>

app/views/blogs/show.html.erb
<style type="text/css">
  #dropzone {
      box-sizing: border-box;
      position: absolute;
      top: 0%;
      left: 0%;
      width: 100%;
      height: 100%;
      border: 2px #ababab dashed;
      text-transform: uppercase;
      font-weight: bold;
      z-index: 2;
    }
    .powered-by {
      position: absolute;
      bottom: 10px;
      left: 0;
      width: 100%;
      text-align: center;
      text-transform: none;
      font-weight: light;
      font-size: 12px;
      line-height: 1.5em;
    }
    .powered-by a {
      color: #92C7FF;
      text-decoration: none;
    }
    #image {
      text-align: center;
    }
    #view-button {
      position: fixed;
      top: 0;
      right: 0;
      padding: 10px;
      font-weight: bold;
      font-size: 10px;
      background-color: #333;
      color: #FFF;
      cursor: pointer;
      z-index: 100;
      text-transform: uppercase;
    }
    #livepreview {
      position: relative;
      top: -100px;
      width: 1200px;
      margin: 0 auto;
      z-index: 99;
    }

    .preview-image {
      line-height: 0;
    }
    .preview-image {
      display: inline-block;
    }
    .preview-image, .cropped-image > div {
      position: relative;
    }
    .cropped-image {
      position: absolute;
      overflow: hidden;
    }
    .preview-image:before {
      content: " ";
      display: block;
      width: 100%;
      height: 100%;
      background-color: #000;
      position: absolute;
      opacity: .7;
    }
    .cropping-code {
      margin: 10px auto 50px;
      display: block;
      width: 100%;
      padding: 10px 0;
      text-align: center;
      border: none;
      outline: none;
      background-color: transparent;
    }
    .cropping-code {
      box-sizing: border-box;
      position: relative;
      bottom: 0px;
      margin: 0px;
      padding: 20px;
      background-color: rgba(0, 0, 0, 0.8);
      color: #FFF;
      font-weight: bold;
      text-align: left;
      max-width: 960px;
    }

    .clear {
      width: 100%;
      clear: both;
    }
  
    .text {
      position: absolute;
      top: 50%;
      left: 50%;
      text-align: center;
      font-size: 24px;
      font-weight: bold;
      text-transform: uppercase;
      -webkit-transform: translate(-50%,-50%);
      -moz-transform: translate(-50%,-50%);
      transform: translate(-50%,-50%);
    }
  
    img {
      -webkit-touch-callout: none;
      -webkit-user-select: none;
      -khtml-user-select: none;
      -moz-user-select: none;
      -ms-user-select: none;
      user-select: none;
      pointer-events: none;
    }
     .black_overlay{
        display: none;
        position: absolute;
        top: 0%;
        left: 0%;
        width: 100%;
        height: 100%;
        background-color: black;
        z-index:1001;
        -moz-opacity: 0.8;
        opacity:.80;
        filter: alpha(opacity=80);
    }
    .white_content {
        display: none;
        position: absolute;
        top: 25%;
        left: 25%;
        width: 50%;
        height: 50%;
        padding: 16px;
        border: 16px solid orange;
        background-color: white;
        z-index:1002;
        overflow: auto;
    }
    .imageholder{
      position: relative;
      width: 100%;
      background: #7E7E7E;
    }

    .imageholder img{
    margin: 0px auto;
    position: relative;
    display: block;}

    
</style>
<div class="container">

	<div class="row">
  <%= link_to 'ReCrop', edit_blog_path(@blog), :class => "btn btn-warning" %> |
  <%= link_to 'Back', blogs_path, :class => "btn btn-info" %> | 
  <a class="btn btn-danger" href= "javascript:void(0)" onclick = "document.getElementById('light').style.display='block';document.getElementById('fade').style.display='block'">Image Names</a>
		<div class="column">
		<p id="notice"><%= notice %></p>

<p>
  <strong>Brand:</strong><br>
  <%= @blog.title %>
</p>

<p>
  <strong>Project Name:</strong><br>
  <%= @blog.description %>
</p>
<p>
  <strong>Links:</strong><br>
  <% if @blog.link.nil? || @blog.link == 0 %>
  <p>There are no links to be shown</p>
  <% else %>
  <p>
    <div class="cropped-image">
    <% @blog.link.html_safe.split("<br /><br />").each do |item| %>   
    <div>
      <div class="imageholder"><img src="<%= item.strip %>"  onError="this.onerror=null;this.src='<%= image_url 'bigimage_placeholder.gif' %>';"></div>
        <p class="cropping-code"><%= item.strip %>&op_sharpen=1</p>
    </div>     
     <br>  

    <% end %>
    </div> 
  </p>

  <% end %>
</p>





</div>
	</div>
</div>


 
<div id="light" class="white_content">

  <p>
  <strong>Image Names:</strong><br>
  <% if @blog.link.nil? || @blog.link == 0 %>
  <p>There are no links to be shown</p>
  <% else %>
  <p>
    <div class="cropped-image">
    <% @blog.link.html_safe.split("<br /><br />").each do |item| %>   
    <div>
        <p><%= item.strip.gsub("http://images.hugoboss.com/is/image/boss/", '').split('?')[0]  %></p>
    </div>     
     <br>  

    <% end %>
    </div> 
  </p>

  <% end %>


  <a style="top: 0px;position: absolute;right: 0px;padding: 20px;" href= "javascript:void(0)" onclick= "document.getElementById('light').style.display='none';document.getElementById('fade').style.display='none'">Close</a></div>
<div id="fade" class="black_overlay"></div>

app/views/guidelines/index.html.erb
<style>
html, body {
	font-size: 18px;
	line-height: 1.5em;
	font-family: Arial;
	color: #222;
}
body {
	margin-top: 2em;
}
ol, p {
	max-width: 660px;
	margin: 2em auto;
}
a {
	color: #41A574;
	text-decoration: none;
}
a:hover {
	text-decoration: underline;
}
.bookmark {
	font-size: 1.618em;
}
</style>
<div class="container">
<%= link_to 'Home', blogs_path, :class => "btn btn-primary reupload gohome" %>
<p>In order to have the tool find the croppings please pay attention to the following guidelines:</p>
<ol>
	<li>Create a folder on which the layer mask is applied</li>
	<li>The folder can be called <strong>img</strong> or any name that contains <strong>image</strong> will do</li>
	<li>Put the high res image inside this folder</li>
	<li><strong>Don't change the name of the image layer</strong></li>
	<li>The structure should look like this:<br /><img src="<%= image_url 'structure.png' %>"></li>
	<li>You can resize the images proportionally and even resave the image with a lower&nbsp;res</li>
	<li>Important is however, that the image itself is as big as or bigger than its layer mask</li>
	<li>Test the croppings with the tool</a></li>

</ol>
</div>